Complete porting for MACI gatekeepers
privacy-scaling-explorations/zk-kit.solidity pull request #31
Opened 2024-07-09 21:07 UTC by 0xjei

## Description
This PR adds the `GitcoinPassportExcubia`, `ZKEdDSAEventTicketPCDExcubia` (prev Zupass) and, `HatsExcubia`. During the porting process, certain interfaces were extended and controls and methods generalised. The code coverage is 100%.

## Related Issue(s)
closes #18 

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn compile` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2024-07-09 21:21 UTC, 0xjei commented
> Slither found more than 20 potential problems in the proposed changes. Check the [Files changed](/privacy-scaling-explorations/zk-kit.solidity/pull/31/files) tab for more details.

these should just be inline-assembly (verifier) and naming (which is a false positive).

2024-07-10 13:28 UTC, ctrlc03 commented on packages/excubiae/contracts/extensions/GitcoinPassportExcubia.sol
> +        passedUsers[passerby] = true;
this should be before super._pass as that's where the external call to the gitcoin passport contract is made (check-effect-interactions)

2024-07-10 13:30 UTC, ctrlc03 commented on packages/excubiae/contracts/extensions/HatsExcubia.sol
> +        for (uint256 i; i < _criterionHats.length; ++i) {
should be cheaper to cache the length before the loop and pass that as counter end condition

2024-07-10 13:31 UTC, ctrlc03 commented on packages/excubiae/contracts/extensions/HatsExcubia.sol
> +        passedUsers[passerby] = true;
would recommend adhering to the checks-effects-interactions pattern and setting the user as passedUser before the external calls

2024-07-10 13:36 UTC, ctrlc03 commented on packages/excubiae/contracts/extensions/ZKEdDSAEventTicketPCDExcubia.sol
> +        passedZKEdDSAEventTicketPCDs[ticketId] = true;
let's move this before super._pass

2024-07-10 13:37 UTC, ctrlc03 commented on packages/excubiae/contracts/extensions/ZKEdDSAEventTicketPCDExcubia.sol
> +        uint256 ticketId = _pubSignals[0];
is it more efficient to create a new var rather than using _pubSignals[0] twice down in the next lines?

2024-07-10 13:38 UTC, ctrlc03 requested changes
Great work, let's some comments

2024-07-10 14:14 UTC, ctrlc03 approved these changes
LGTM

2024-07-10 14:39 UTC, cedoor approved these changes
I haven't checked all the implementation details but overall looks good to me!

2024-07-10 14:41 UTC, merged